nuitka api_server.py ^
  --standalone ^
  --output-dir=build ^
  --enable-plugin=tk-inter ^
  --windows-console-mode=disable ^
  --include-data-dir=%USERPROFILE%\AppData\Local\ms-playwright=ms-playwright ^
  --include-package=common ^
  --include-package=recorder ^
  --include-package=ui ^
  --include-data-dir=javascript=javascript ^
  --include-data-file=agent_config.json=agent_config.json ^
  --include-data-dir=myenv/Lib/site-packages/dateparser/data=dateparser/data ^
  --include-data-dir=myenv\Lib\site-packages\playwright\driver\package\.local-browsers=playwright/driver/package/.local-browsers ^
  --include-data-files=myenv/Lib/site-packages/playwright/driver/package/.local-browsers/chromium-1169/chrome-win/*.dll=playwright/driver/package/.local-browsers/chromium-1169/chrome-win ^
  --include-data-files=myenv/Lib/site-packages/playwright/driver/package/.local-browsers/chromium-1169/chrome-win/*.exe=playwright/driver/package/.local-browsers/chromium-1169/chrome-win ^
  --show-progress
